---
title: "graphs"
format: html
editor_options: 
  chunk_output_type: console
---


### Load Libraries

```{r}
library(DBI)
library(duckdb)
library(dtplyr)
library(ggplot2)
```

### Call data in from Duckdb

```{r}
con <- dbConnect(duckdb(), dbdir = "D:/MEDS/madison_lake_data_analysis/wisconsin_data.duckdb")
dbListTables(con)
```

### Query Data

```{r}
# Query data
ice_temp_data <- dbGetQuery(con, "SELECT year, avg_snow_raw_cm, avg_ice_duration
  FROM year
  ORDER BY year
")
```

```{r}
# View queried data
head(ice_temp_data)
```

### Visualize data

```{r}
ggplot(ice_temp_data) +
  # Points for snow vs. ice
  geom_point(aes(x = avg_snow_raw_cm, y = avg_ice_duration, color = "Snowfall (cm) vs Ice Duration"),
             size = 3, alpha = 0.7) +
  # Trend line
  geom_smooth(aes(x = avg_snow_raw_cm, y = avg_ice_duration, color = "Trend Line"),
              method = "lm", linewidth = 1, alpha = 0.2) +
  # Manual legend
  scale_color_manual(
    name = "Legend",
    values = c(
      "Snowfall (cm) vs Ice Duration" = "#2c7fb8",
      "Trend Line" = "#08306b"
    )
  ) +
  # Labels and theme
  labs(
    title = "Snowfall vs. Ice Duration",
    x = "Snowfall (cm)",
    y = "Ice Duration (days)"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "sans"),
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    axis.title = element_text(size = 11),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "gray90"),
    legend.position = "bottom"
  )

```

